---
title: "p8105_hw5_SL5454"
author: "Sining Leng"
date: "2024-11-07"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)
```

## Problem 1
```{r}
bday = function(n) {

  bdays = sample(1:365, size = n, replace = TRUE)
  
  duplicate = length(unique(bdays)) < n

  return(duplicate)
  
}

bday_samp = 
  expand_grid(
    n = 2:50,
    iter = 1:10000
  ) |> 
  mutate(res = map_lgl(n, bday)) |> 
  group_by(n) |> 
  summarize(prob = mean(res))

bday_samp |>
  ggplot(aes(x = n, y = prob)) + 
  geom_line()
```

The probability that at least two people in the group will share a birthday increasing with group size. Around group size of 23, the probability exceeds 50%.


## Problem 2

```{r}
t_test = function(n = 30, sigma = 5, mu) {
  
  data = rnorm(n, mean = mu, sd = sigma)
  
  ttest_result = t.test(data, mu = 0, conf.level = 0.95) |>
    broom::tidy()
  
  return(ttest_result)
}

set.seed(123)
mu_df = 
  expand_grid(
    mu = 0:6,
    iter = 1:5000
  ) |>
  mutate(output = map(mu, ~t_test(mu = .x))) |>
  unnest(output)

```

Repeat mu = 0:6
```{r}
rejected =
  mu_df |>
  group_by(mu) |>
  summarize(
    power = mean(p.value < 0.05),
    avg_est = mean(estimate),
    avg_reject = mean(estimate[p.value < 0.05])
  )
```

Plot "Power vs. Mu"
```{r}
rejected |>
ggplot(aes(x = mu, y = power)) +
  geom_line() +
  labs(title = "Power of t-test vs. True Value of mu",
       x = "mu",
       y = "Power") +
  theme_minimal()
```

The plot shows that the greater the effective size the larger the power of this t test.
